sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23

before_install:
- chmod +x gradlew

script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"

after_success:
- sh set_tags.sh

notifications:
  email: true

deploy:
  provider: releases
  api_key:  ded7e499c2770d264b431d375f7984c00ad013dd 
  skip_cleanup: true
  on:
    branch: master
    repo: lianghuacheng/AutoDeployExample


before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
